/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abitudine;

/**
 *
 * @author Cristian
 */
public class AbitudineDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AbitudineDashboard
     */
    public AbitudineDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon("C:/Users/Cristian/Downloads/AbitudineLogo (1).png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbitudineLogoClick = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        DashboardBtn = new javax.swing.JLabel();
        ScheduleBtn = new javax.swing.JLabel();
        TaskBtn = new javax.swing.JLabel();
        GWACalculator = new javax.swing.JLabel();
        ProfileBtn = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Dashboard = new javax.swing.JTabbedPane();
        Abitudine_Dashboard = new javax.swing.JPanel();
        Abitudine_Schedule = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Abitudine_Tasks = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Abitudine_Calculator = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Abitudine_Profile = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abitudine");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(787, 432));
        setResizable(false);
        getContentPane().setLayout(null);

        AbitudineLogoClick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbitudineLogoClick.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristian\\Downloads\\Your paragraph text (100 x 100 px) (80 x 80 px).png")); // NOI18N
        AbitudineLogoClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AbitudineLogoClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbitudineLogoClickMouseClicked(evt);
            }
        });
        getContentPane().add(AbitudineLogoClick);
        AbitudineLogoClick.setBounds(10, 10, 110, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 790, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NAME");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(603, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 790, 60);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 310, 40, 23);

        DashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DashboardBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristian\\Downloads\\AbitudineFile (9).png")); // NOI18N
        DashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardBtnMouseClicked(evt);
            }
        });
        jPanel1.add(DashboardBtn);
        DashboardBtn.setBounds(10, 30, 40, 40);

        ScheduleBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScheduleBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristian\\Downloads\\AbitudineFile\\2.png")); // NOI18N
        ScheduleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ScheduleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduleBtnMouseClicked(evt);
            }
        });
        jPanel1.add(ScheduleBtn);
        ScheduleBtn.setBounds(10, 80, 40, 30);

        TaskBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristian\\Downloads\\AbitudineFile\\3.png")); // NOI18N
        TaskBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TaskBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaskBtnMouseClicked(evt);
            }
        });
        jPanel1.add(TaskBtn);
        TaskBtn.setBounds(10, 120, 40, 40);

        GWACalculator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GWACalculator.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristian\\Downloads\\AbitudineFile\\4.png")); // NOI18N
        GWACalculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GWACalculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GWACalculatorMouseClicked(evt);
            }
        });
        jPanel1.add(GWACalculator);
        GWACalculator.setBounds(10, 170, 40, 30);

        ProfileBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristian\\Downloads\\AbitudineFile (10).png")); // NOI18N
        ProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileBtnMouseClicked(evt);
            }
        });
        jPanel1.add(ProfileBtn);
        ProfileBtn.setBounds(10, 210, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 60, 380);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(60, 60, 10, 380);

        Abitudine_Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Abitudine_DashboardLayout = new javax.swing.GroupLayout(Abitudine_Dashboard);
        Abitudine_Dashboard.setLayout(Abitudine_DashboardLayout);
        Abitudine_DashboardLayout.setHorizontalGroup(
            Abitudine_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        Abitudine_DashboardLayout.setVerticalGroup(
            Abitudine_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        Dashboard.addTab("Dashboard", Abitudine_Dashboard);

        Abitudine_Schedule.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout Abitudine_ScheduleLayout = new javax.swing.GroupLayout(Abitudine_Schedule);
        Abitudine_Schedule.setLayout(Abitudine_ScheduleLayout);
        Abitudine_ScheduleLayout.setHorizontalGroup(
            Abitudine_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Abitudine_ScheduleLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        Abitudine_ScheduleLayout.setVerticalGroup(
            Abitudine_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Abitudine_ScheduleLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        Dashboard.addTab("Schedule", Abitudine_Schedule);

        Abitudine_Tasks.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tab 3");

        javax.swing.GroupLayout Abitudine_TasksLayout = new javax.swing.GroupLayout(Abitudine_Tasks);
        Abitudine_Tasks.setLayout(Abitudine_TasksLayout);
        Abitudine_TasksLayout.setHorizontalGroup(
            Abitudine_TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Abitudine_TasksLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel3)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        Abitudine_TasksLayout.setVerticalGroup(
            Abitudine_TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Abitudine_TasksLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel3)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        Dashboard.addTab("Tasks", Abitudine_Tasks);

        Abitudine_Calculator.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Tab 4");

        javax.swing.GroupLayout Abitudine_CalculatorLayout = new javax.swing.GroupLayout(Abitudine_Calculator);
        Abitudine_Calculator.setLayout(Abitudine_CalculatorLayout);
        Abitudine_CalculatorLayout.setHorizontalGroup(
            Abitudine_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Abitudine_CalculatorLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel4)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        Abitudine_CalculatorLayout.setVerticalGroup(
            Abitudine_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Abitudine_CalculatorLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel4)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        Dashboard.addTab("Calculator", Abitudine_Calculator);

        Abitudine_Profile.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Tab 6");

        javax.swing.GroupLayout Abitudine_ProfileLayout = new javax.swing.GroupLayout(Abitudine_Profile);
        Abitudine_Profile.setLayout(Abitudine_ProfileLayout);
        Abitudine_ProfileLayout.setHorizontalGroup(
            Abitudine_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Abitudine_ProfileLayout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(323, 323, 323))
        );
        Abitudine_ProfileLayout.setVerticalGroup(
            Abitudine_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Abitudine_ProfileLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel5)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        Dashboard.addTab("Profile", Abitudine_Profile);

        getContentPane().add(Dashboard);
        Dashboard.setBounds(60, -40, 730, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AbitudineLogoClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbitudineLogoClickMouseClicked
        Dashboard.setSelectedIndex(0);
    }//GEN-LAST:event_AbitudineLogoClickMouseClicked

    private void DashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardBtnMouseClicked
        Dashboard.setSelectedIndex(0);
    }//GEN-LAST:event_DashboardBtnMouseClicked

    private void TaskBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskBtnMouseClicked
        Dashboard.setSelectedIndex(2);
    }//GEN-LAST:event_TaskBtnMouseClicked

    private void ScheduleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleBtnMouseClicked
        Dashboard.setSelectedIndex(1);
    }//GEN-LAST:event_ScheduleBtnMouseClicked

    private void GWACalculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GWACalculatorMouseClicked
        Dashboard.setSelectedIndex(3);
    }//GEN-LAST:event_GWACalculatorMouseClicked

    private void ProfileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileBtnMouseClicked
        Dashboard.setSelectedIndex(4);
    }//GEN-LAST:event_ProfileBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbitudineDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbitudineDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbitudineDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbitudineDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbitudineDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AbitudineLogoClick;
    private javax.swing.JPanel Abitudine_Calculator;
    private javax.swing.JPanel Abitudine_Dashboard;
    private javax.swing.JPanel Abitudine_Profile;
    private javax.swing.JPanel Abitudine_Schedule;
    private javax.swing.JPanel Abitudine_Tasks;
    private javax.swing.JTabbedPane Dashboard;
    private javax.swing.JLabel DashboardBtn;
    private javax.swing.JLabel GWACalculator;
    private javax.swing.JLabel ProfileBtn;
    private javax.swing.JLabel ScheduleBtn;
    private javax.swing.JLabel TaskBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
