/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abitudine;

import java.util.Date;
import javax.swing.JOptionPane;


        
public class AddHabitForm extends javax.swing.JFrame {

    /**
     * Creates new form AddHabitForm
     */
    public AddHabitForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TaskName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        StatusType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PriorityType = new javax.swing.JComboBox<>();
        jlabel = new javax.swing.JLabel();
        CategoryType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OptionalNotes = new javax.swing.JTextArea();
        AddTaskBtn = new javax.swing.JButton();
        DueDate = new de.wannawork.jcalendar.JCalendarComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 565));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(350, 544));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 544));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 544));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADD TASK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 350, 60);

        TaskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskNameActionPerformed(evt);
            }
        });
        jPanel1.add(TaskName);
        TaskName.setBounds(30, 130, 280, 30);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Task Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 110, 120, 14);

        StatusType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Started", "In Progress", "Completed", "On Hold ", "Delayed", " " }));
        StatusType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTypeActionPerformed(evt);
            }
        });
        jPanel1.add(StatusType);
        StatusType.setBounds(30, 190, 130, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Status");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 37, 16);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Due Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 170, 60, 14);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Priority");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 230, 70, 16);

        PriorityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Medium", "Low" }));
        jPanel1.add(PriorityType);
        PriorityType.setBounds(30, 250, 280, 30);

        jlabel.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jlabel.setForeground(new java.awt.Color(153, 153, 153));
        jlabel.setText("Category");
        jPanel1.add(jlabel);
        jlabel.setBounds(30, 290, 70, 14);

        CategoryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Health", "Education", "Work", "Personal", "Finance", "Spiritual", "Social", "Fitness", "Creativity", "Productivity" }));
        jPanel1.add(CategoryType);
        CategoryType.setBounds(30, 310, 280, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel6.setText("Notes");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 360, 29, 14);

        OptionalNotes.setColumns(20);
        OptionalNotes.setLineWrap(true);
        OptionalNotes.setRows(5);
        jScrollPane1.setViewportView(OptionalNotes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 380, 280, 110);

        AddTaskBtn.setBackground(new java.awt.Color(255, 153, 0));
        AddTaskBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AddTaskBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddTaskBtn.setText("ADD TASK");
        AddTaskBtn.setBorder(null);
        AddTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskBtnActionPerformed(evt);
            }
        });
        AddTaskBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddTaskBtnKeyPressed(evt);
            }
        });
        jPanel1.add(AddTaskBtn);
        AddTaskBtn.setBounds(70, 510, 200, 30);
        jPanel1.add(DueDate);
        DueDate.setBounds(170, 190, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StatusTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusTypeActionPerformed

    private void TaskNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskNameActionPerformed

    private void AddTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskBtnActionPerformed
         String task = TaskName.getText();
         String status = (String) StatusType.getSelectedItem(); 
         Date selectedDate = DueDate.getDate();
         String priority = (String) PriorityType.getSelectedItem();
         String category = (String) CategoryType.getSelectedItem();
         String notes = OptionalNotes.getText();

         String taskName = TaskName.getText().trim();
         if (taskName.isEmpty()) {
             // Show warning dialog if task name is empty
             JOptionPane.showMessageDialog(
                 this, 
                 "Please designate a task name before adding the task.", 
                 "Task Name Required", 
                 JOptionPane.WARNING_MESSAGE
             );
             return;
         } else {
             // Save task to database
             boolean saveSuccessful = AbitudineTasksDatabase.saveTask(
                 task, status, selectedDate, priority, category, notes
             );

             if (saveSuccessful) {
                 // Show confirmation message
                 JOptionPane.showMessageDialog(
                     this,
                     "New habit successfully added!",
                     "Success",
                     JOptionPane.INFORMATION_MESSAGE
                 );

                 // Close this form
                 this.dispose();
             } else {
                 // Show error message
                 JOptionPane.showMessageDialog(
                     this,
                     "Error saving habit. Please try again.",
                     "Error",
                     JOptionPane.ERROR_MESSAGE
                 );
             }
         }
    }//GEN-LAST:event_AddTaskBtnActionPerformed

    private void AddTaskBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddTaskBtnKeyPressed
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
           AddTaskBtn.doClick(); // Simulates a button click
       }
    }//GEN-LAST:event_AddTaskBtnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHabitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHabitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHabitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHabitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddHabitForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskBtn;
    private javax.swing.JComboBox<String> CategoryType;
    private de.wannawork.jcalendar.JCalendarComboBox DueDate;
    private javax.swing.JTextArea OptionalNotes;
    private javax.swing.JComboBox<String> PriorityType;
    private javax.swing.JComboBox<String> StatusType;
    private javax.swing.JTextField TaskName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    // End of variables declaration//GEN-END:variables

    private void clearFormFields() {
        TaskName.setText("");
        StatusType.setSelectedIndex(0);
        DueDate.setDate(new Date()); // Reset to current date
        PriorityType.setSelectedIndex(0);
        CategoryType.setSelectedIndex(0);
        OptionalNotes.setText("");
        TaskName.requestFocus();
    }
}
